# Generated by Django 5.2.5 on 2025-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaventa',
            name='centrocosto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de Costo'),
        ),
    ]
