# Generated by Django 5.2.5 on 2025-10-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0003_auto_20251024_1513'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Oferta',
                'verbose_name_plural': 'Estados de Oferta',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(max_length=20, unique=True)),
                ('fecha_oferta', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('area_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areaventa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.estado')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-fecha_oferta'],
            },
        ),
        migrations.CreateModel(
            name='OfertaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ofertas.oferta')),
            ],
            options={
                'verbose_name': 'Item de Oferta',
                'verbose_name_plural': 'Items de Oferta',
            },
        ),
    ]
