# Generated by Django 5.2.7 on 2025-10-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofertas.estado'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
