# Generated by Django 5.2.7 on 2025-10-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_oferta_estado_alter_oferta_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
