# Generated by Django 5.2.7 on 2025-10-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_remove_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='fecha_vencimiento',
        ),
    ]
