# Generated by Django 5.2.7 on 2025-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_contrato', models.CharField(max_length=50)),
                ('fecha_contrato', models.DateField()),
                ('codigo_reeup', models.CharField(max_length=50)),
                ('codigo_nit', models.CharField(max_length=50)),
                ('cuenta_bancaria_cup', models.CharField(max_length=50)),
                ('direccion_postal', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefonos', models.CharField(max_length=255)),
                ('nombre_director', models.CharField(max_length=255)),
                ('ci_director', models.CharField(max_length=20)),
                ('nombre_economico', models.CharField(max_length=255)),
                ('ci_economico', models.CharField(max_length=20)),
                ('nombre_autorizado1', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_autorizado1', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_autorizado2', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_autorizado2', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_autorizado3', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_autorizado3', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
