# Generated by Django 5.2.7 on 2025-10-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_contrato_pdf_and_more'),
    ]

    operations = [
    ]
