# Generated by Django 5.2.7 on 2025-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20251024_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clienteversat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuentaversat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
