# Generated by Django 5.2.5 on 2025-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_estado_factura_observaciones_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
